src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $start_time = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $picture = null;

    #[ORM\Column]
    private ?int $capacity = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column]
    private ?int $phone_number = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(length: 255)]
    private ?string $street_name = null;

    #[ORM\Column]
    private ?int $house_number = null;

    #[ORM\Column]
    private ?int $zip_code = null;

    #[ORM\Column(length: 255)]
    private ?string $event_url = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getStartTime(): ?\DateTimeInterface
    {
        return $this->start_time;
    }

    public function setStartTime(\DateTimeInterface $start_time): self
    {
        $this->start_time = $start_time;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(int $capacity): self
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhoneNumber(): ?int
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(int $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getStreetName(): ?string
    {
        return $this->street_name;
    }

    public function setStreetName(string $street_name): self
    {
        $this->street_name = $street_name;

        return $this;
    }

    public function getHouseNumber(): ?int
    {
        return $this->house_number;
    }

    public function setHouseNumber(int $house_number): self
    {
        $this->house_number = $house_number;

        return $this;
    }

    public function getZipCode(): ?int
    {
        return $this->zip_code;
    }

    public function setZipCode(int $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getEventUrl(): ?string
    {
        return $this->event_url;
    }

    public function setEventUrl(string $event_url): self
    {
        $this->event_url = $event_url;

        return $this;
    }
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, ["attr"=>["placeholder" => "Please type", "class" => "form-control  w-75 mb-2" ]])
            ->add('date', DateTimeType::class, ["attr" =>["class"=>"form-control  w-75 mb-2",'format' => 'yyyy-MM-dd']])
            ->add('start_time', DateTimeType::class, ["attr" =>["class"=>"form-control  w-75 mb-2"]])
            ->add('description', TextareaType::class,  ["attr"=>["placeholder" => "Please type a description...", "class" => "form-control  w-75 mb-2" ]])
            ->add('picture', TextType::class, [
                'label' => 'Picture',
                'attr' => ['class' => 'form-control w-75', 'style' => 'margin-bottom:2rem;', 'placeholder'=>'Picture']])
            ->add('capacity',  NumberType::class, [
                'label' => 'Number of People',
                'attr' => ['class' => 'form-control w-75', 'style' => 'margin-bottom:2rem;', 'placeholder'=>'Number of People']
            ])
            ->add('email', EmailType::class, [
                'label' => 'Email Address',
                'attr' => ['class' => 'form-control w-75', 'style' => 'margin-bottom:2rem;', 'placeholder'=>'Email Address']])
            ->add('phone_number', NumberType::class, [
                'label' => 'Phone Number',
                'attr' => ['class' => 'form-control w-75', 'style' => 'margin-bottom:2rem;', 'placeholder'=>'Phone Number']
            ])
            ->add('city', ChoiceType::class, [
                'choices' => ['Vienna' => 'Vienna', 'Upper Austria' => 'Upper Austria', 'Lower Austria' => 'Lower Austria', 'Styria' => 'Styria', 'Carinthia' =>'Carinthia', 'Vorarlberg'=>"Vorarlberg"],
                'attr' => ['class' => 'form-control w-75', 'style' => 'margin-bottom:2rem']
            ])
            ->add('street_name',  TextType::class, [
                'label' => 'Street Name',
                'attr' => ['class' => 'form-control w-75', 'style' => 'margin-bottom:2rem;', 'placeholder'=>'Street Name']
            ])
            ->add('house_number',  NumberType::class, [
                'label' => 'House Number',
                'attr' => ['class' => 'form-control w-75', 'style' => 'margin-bottom:2rem;', 'placeholder'=>'House Number']
            ])
            ->add('zip_code', NumberType::class, [
                'label' => 'Zip Code',
                'attr' => ['class' => 'form-control w-75', 'style' => 'margin-bottom:2rem;', 'placeholder'=>'Zip Code']
            ])
            ->add('event_url', UrlType::class, [
                'label' => 'Event Website',
                'attr' => ['class' => 'form-control w-75', 'style' => 'margin-bottom:2rem;', 'placeholder'=>'Event Website']
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\EventType;
use App\Repository\EventRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

//#[Route('/event')]
class EventController extends AbstractController
{
    #[Route('/', name: 'app_event_index', methods: ['GET'])]
    public function index(EventRepository $eventRepository): Response
    {
        return $this->render('event/index.html.twig', [
            'events' => $eventRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_event_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EventRepository $eventRepository): Response
    {
        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $eventRepository->save($event, true);

            return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('event/new.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_event_show', methods: ['GET'])]
    public function show(Event $event): Response
    {
        return $this->render('event/show.html.twig', [
            'event' => $event,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_event_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Event $event, EventRepository $eventRepository): Response
    {
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $eventRepository->save($event, true);

            return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('event/edit.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

   /* #[Route('/delete/{id}', name: 'app_event_delete', methods: ['POST'])]
    public function delete(Request $request, Event $event, EventRepository $eventRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$event->getId(), $request->request->get('_token'))) {
            $eventRepository->remove($event, true);
        }

        return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
    }*/

    #[Route('/delete/{id}', name: 'app_event_delete')]
    public function deleteAction($id, ManagerRegistry $doctrine): Response
    {
        $em = $doctrine->getManager();
        $event = $doctrine->getRepository(Event::class)->find($id);
        $em->remove($event);
        $em->flush();

        return $this->redirectToRoute('app_event_index');
    }
}

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('app_event_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/event/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <style>
    #event{
        color:white;
    }
    .btn{

        margin-bottom: 5%;
    }
    </style>
    <button class="btn btn-primary mb-2">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Event{% endblock %}


{% block body %}
<style>
    body {
        background-color: rgb(19, 27, 55);
    }
</style>

<h1 style="color:white ;">Edit Event</h1>

{{ include('event/_form.html.twig', {'button_label': 'Update'}) }}

<a class="btn btn-primary" href="{{ path('app_event_index') }}">Back to List</a>

{{ include('event/_delete_form.html.twig') }}
{% endblock %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event index{% endblock %}



{% block body %}

{% include "components/hero.html.twig" %}

<div class="container mt-3 mb-2">
    <div class="row">
        {% for event in events %}

        <div class="col-lg-4 col-md-6 col-sm-12 p-4">
            <div class="card" style="width: 18rem;">
                <img src="{{asset('picture/'~ event.picture)}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{event.name}}</h5>
                    <p class="card-text">{{event.description}}</p>
                    <p class="card-text">{{event.startTime|date('d.m.Y g:i')}}</p>
                    <a href="/{{event.id}}" class="btn btn-outline-success">Details</a>
                    <a href="{{event.id}}/edit" class="btn btn-outline-dark">Edit</a>
                    <a href="/delete/{{event.id}}" class="btn btn-danger">Delete</a>
                </div>
            </div>
        </div>

        {% endfor %}






        {# <a href="{{ path('app_event_new') }}">Create new</a> #}
        {% endblock %}

templates/event/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Event{% endblock %}

{% block body %}
<style>
    body {
        background-color: rgb(19, 27, 55);

    }
</style>
<h1 style="color:white ;">Create Event</h1>

{{ include('event/_form.html.twig') }}

<a class="btn btn-success" href="{{ path('app_event_index') }}">Back to list</a>
{% endblock %}

templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event{% endblock %}

{% block body %}

<div class="card bg-dark text-white">
    <img src="{{asset('picture/'~ event.picture)}}" class="card-img" alt="...">
    <div class="card-img-overlay">
        <h1 class="card-title text-secondary">{{event.name}}</h1>
        <p class="card-text detail_info text-secondary"><b>Date: </b>{{event.date|date('F j, Y, g:i a')}}</p>
        <p class="card-text detail_info text-secondary"><b>Start Time: </b>{{event.startTime|date('F j, Y, g:i a')}}</p>
        <p class="card-text detail_info text-secondary"><b>Email Address: </b>{{event.email}}</p>
        <p class="card-text detail_info text-secondary"><b>Number of People: </b>{{event.capacity}}</p>
        <p class="card-text detail_info text-secondary"><b>Phone Number: </b>{{event.phoneNumber}}</p>
        <p class="card-text detail_info text-secondary"><b>City: </b>{{event.city}}</p>
        <p class="card-text detail_info text-secondary"><b>Street Name: </b>{{event.streetName}}</p>
        <p class="card-text detail_info text-secondary"><b>House Number: </b>{{event.houseNumber}}</p>
        <p class="card-text detail_info text-secondary"><b>Zip Code: </b>{{event.zipCode}}</p>
        <p class="card-text detail_info text-secondary"><b>Event Website: </b>{{event.eventUrl}}</p>
        <p class="card-text detail_info text-secondary"><b>Description: </b>{{event.description}}</p>
        <div class="col-12 mt-2">
            <a href="/{{event.id}}/edit"><button class="btn btn-warning"
                    type="button">Edit</button></a>
            <a href="/"><button class="btn btn-secondary" type="button">Home</button></a>
            <a href="/delete/{{event.id}}"><button class="btn btn-danger "
                    type="button">Delete</button></a>
        </div>
    </div>
</div>


{# <div class="card">
    <div class="row">
        <div class="col-md-4">
            <img src="{{asset('picture/'~ event.picture)}}" class="class=" image-fluid" alt="...">
        </div>
        <div class="col-md-8 ">
            <div class="card-body">
                <h5 class="card-title detail_title detail_info">{{event.name}}</h5>
                <p class="card-text detail_info"><b>Date: </b>{{event.date|date('F j, Y, g:i a')}}</p>
                <p class="card-text detail_info"><b>Start Time: </b>{{event.startTime|date('F j, Y, g:i a')}}</p>
                <p class="card-text detail_info"><b>Email Address: </b>{{event.email}}</p>
                <p class="card-text detail_info"><b>Number of People: </b>{{event.capacity}}</p>
                <p class="card-text detail_info"><b>Phone Number: </b>{{event.phoneNumber}}</p>
                <p class="card-text detail_info"><b>City: </b>{{event.city}}</p>
                <p class="card-text detail_info"><b>Street Name: </b>{{event.streetName}}</p>
                <p class="card-text detail_info"><b>House Number: </b>{{event.houseNumber}}</p>
                <p class="card-text detail_info"><b>Zip Code: </b>{{event.zipCode}}</p>
                <p class="card-text detail_info"><b>Event Website: </b>{{event.eventUrl}}</p>
                <p class="card-text detail_info"><b>Description: </b>{{event.description}}</p>
            </div>

            <div class="col-12">
                <a href="/{{event.id}}/edit"><button class="button btn btn-outline-warning detail_button"
                        type="button">Edit</button></a>
                <a href="/"><button class="button button2 btn btn-outline-secondary" type="button">Home</button></a>
                <a href="/delete/{{event.id}}"><button class="button button2 btn btn-outline-danger "
                        type="button">Delete</button></a>
            </div>
        </div>
    </div>
</div>
</div> #}

{# <table class="table">
    <tbody>
        <tr>
            <th>Id</th>
            <td>{{ event.id }}</td>
        </tr>
        <tr>
            <th>Name</th>
            <td>{{ event.name }}</td>
        </tr>
        <tr>
            <th>Date</th>
            <td>{{ event.date ? event.date|date('Y-m-d H:i:s') : '' }}</td>
        </tr>
        <tr>
            <th>Start_time</th>
            <td>{{ event.startTime ? event.startTime|date('Y-m-d H:i:s') : '' }}</td>
        </tr>
        <tr>
            <th>Description</th>
            <td>{{ event.description }}</td>
        </tr>
        <tr>
            <th>Picture</th>
            <td>{{ event.picture }}</td>
        </tr>
        <tr>
            <th>Capacity</th>
            <td>{{ event.capacity }}</td>
        </tr>
        <tr>
            <th>Email</th>
            <td>{{ event.email }}</td>
        </tr>
        <tr>
            <th>Phone_number</th>
            <td>{{ event.phoneNumber }}</td>
        </tr>
        <tr>
            <th>City</th>
            <td>{{ event.city }}</td>
        </tr>
        <tr>
            <th>Street_name</th>
            <td>{{ event.streetName }}</td>
        </tr>
        <tr>
            <th>House_number</th>
            <td>{{ event.houseNumber }}</td>
        </tr>
        <tr>
            <th>Zip_code</th>
            <td>{{ event.zipCode }}</td>
        </tr>
        <tr>
            <th>Event_url</th>
            <td>{{ event.eventUrl }}</td>
        </tr>
    </tbody>
</table> #}

{# <a href="{{ path('app_event_index') }}">back to list</a>

<a href="{{ path('app_event_edit', {'id': event.id}) }}">edit</a>

{{ include('event/_delete_form.html.twig') }} #}
{% endblock %}